
#' Hysteresis Index and First Flush Index Function
#'
#' Calculates Hysteresis Index after Lawler (2006) and First Flush Index of a single storm event hydrograph and concentration record.\cr
#' Hysteresis Index of each segment (k) is calculated as by comparing concentration measured at the rising limb and at the falling limb of the hydrograph. For more detail see Lawler, D., Petts, G., Foster, I., & Harper, S. (2006). Turbidity dynamics during spring storm events in an urban headwater river system: The Upper Tame, West Midlands, UK. Science of the Total Environment 360, 109-126.\cr
#' First Flush Index is defined as the amount of load generated by the first x\% of flow , e.g. FF25 criteria used the first 25\% of flow and FF30 criteria used the first 30\% of flow. The value is obtained by plotting the normalised cumulative load against normalised cumulative flow. For more details see Obermann, M., Rosenwinkel, K.-H., & Tournoud, M.-G. (2009). Investigation of first flushes in a medium-sized mediterranean catchment. Journal of Hydrology, 373, 405-415. doi:doi:10.1016/j.jhydrol.2009.04.038
#' @param Event_XTS Xts matrix of flow on the first column and concentration of any contaminant species on the second column. Ideally no NA values are present and the time step is even. (NA could be replaced with zeros if present. To unify the the time step the Add.Na function could be used.)
#' @param k numeric of the first segment of hysteresis and the equal interval for calculation of Hysteresis Index. For instance, k=0.1 means hysteresis is divided into 10 equal parts and HI is calculated for 9 segments (at 0.1,0.2,0.3,...,0.9); k=0.01 means hysteresis is divided into 100 equal parts and HI is calculated for 99 segments (at 0.01,0.02,0.03,...,0.99)
#' @param FFx numeric of the first discharge proportion where proportion of generated load to be determined. For instance, FFx=0.25 for FF25 criteria, FFx=0.30 for FF30 criteria.
#' @keywords hysteresis, hysteresis index, first flush, first flush index
#' @return A list.\cr
#' [[1]] -> Hysteresis Index (HI) as numeric\cr
#' [[2]] -> First-Flush Index (FFx) as numeric\cr
#' @examples
#' x=seq(0,7.9,0.1)
#' base_flow=0.2*sin(x)
#' flow_peak=8*dnorm(x = x,mean = 4)
#' base_tracer=0.7
#' tracer_peak=6*dnorm(x = x,mean = 3)
#' timestamp=seq(from=as.POSIXct("2018-01-01 00:00"),by="hour",length.out = 80)
#' flow=xts(base_flow+flow_peak,order.by=timestamp)
#' conc=xts(base_tracer+tracer_peak,order.by = timestamp)
#' data=cbind(flow,conc)
#' DynPlot(data,Axis = c(1,2))
#' stormindex=EventIndex(data,0.1,0.25)
#' @export
EventIndex = function(Event_XTS,k,FFx){
  ggev=Event_XTS
  ggev$load=ggev[,1]*ggev[,2]
  x=cumsum(ggev[,1]);y=cumsum(ggev[,3])
  Qx=FFx*(max(x)-min(x))+min(x)
  Lx=approx(cbind(x,y),y=NULL,xout = Qx)[2]
  FF=as.numeric(Lx)/max(y)
  ggev[,1]=ggev[,1]/max(ggev[,1], na.rm=T)
  ggev[,2]=ggev[,2]/max(ggev[,2], na.rm=T)
  a=ggev[c(1:which.max(ggev[,1])),c(1,2)]
  b=ggev[c(which.max(ggev[,1]):length(ggev[,1])),c(1,2)]
  Qmax=max(ggev[,1]); Qmin=min(ggev[,1])
  Cmax=max(ggev[,2]); Cmin=min(ggev[,2])

  i=NULL
  j=NULL
  Qi=NULL
  C1=NULL
  C2=NULL
  d=NULL
  for(i in seq(k,1-k,k)){
    j=i
    Qi=j*(Qmax-Qmin)+Qmin
    C1=approx(a,y=NULL,xout = Qi)[2]
    C2=approx(b,y=NULL,xout = Qi)[2]
    d=rbind(d,data.frame(k=j, Qi=Qi, CRL= C1, CFL=C2))
  }
  d1=d[c(which(!is.na(d[,3] & d[,4]))),]

  for(i in 1:nrow(d1)){
    if(d1[i,3]<d1[i,4]){
      d1$HI[i]=1-(1/(d1[i,3]/d1[i,4]))
    }else if(d1[i,3]>=d1[i,4]){
      d1$HI[i]=(d1[i,3]/d1[i,4])-1
    }else{
      NULL
    }
  }
  HImean = mean(d1$HI)
  s=max(ggev[,1])/max(ggev[,2])
  plot1= ggplot(Event_XTS, aes(x=Index))+geom_line(aes(y=Event_XTS[,1], colour="Q"))+geom_line(aes(y=Event_XTS[,2]*s, colour="conc"))+
    scale_y_continuous(sec.axis=sec_axis(~./s, name = "Concentration"))+
    scale_colour_manual(values = c("blue", "black"))+
    labs(y = "Discharge",x = "Date",colour = "Parameter")+theme_bw()+
    theme(legend.position = c(0.79, 0.86))+scale_x_datetime(date_labels ="%b-%d\n%H:%M")
  labels=pretty(index(Event_XTS),3)
  plot2= ggplot(Event_XTS,aes(x=Event_XTS[,1],y=Event_XTS[,2], colour=as.integer(as.POSIXct(index(Event_XTS)))))+geom_point()+
    labs(x = "Discharge", y = "Concentration")+
    scale_colour_gradient(limits=as.integer(as.POSIXct(c(index(Event_XTS)[1],index(Event_XTS)[nrow(Event_XTS)]))),
                          low = "red", high = "blue", name="Date",breaks = as.integer(labels),
                          labels = format(labels, "%m/%d\n%H:%M"))+theme_bw()+
    theme(legend.direction = "horizontal",legend.title=element_text(size=10),legend.text=element_text(size=rel(0.75)),legend.position = c(0.63, 0.12))
  gridExtra::grid.arrange(plot1, plot2, nrow = 1)
  result=list(HImean,FF)
  names(result)=c("Hysteresis Index","First Flush Index")
  return(result)
}

#' Base Flow Index Function
#'
#' Calculates Base Flow Index of a flow hydrograph (Gustard et al. 1992)
#' @param Flow_XTS Xts vector of flow hydrograph with minimum duration of five days. Ideally no NA values are present and the time step is even. (NA could be replaced with zeros if present. To unify the the time step the Add.Na function could be used.)
#' @keywords baseflow
#' @return A list.\cr
#' [[1]] -> Base Flow Index (BFI) as numeric\cr
#' [[2]] -> daily mean, five day minima, and baseflow as matrix\cr
#' @examples
#' TS=DummyTS(days=30)
#' BaseFlowTS=BaseFlow(TS)
#' @export
BaseFlow = function(Flow_XTS){
  daily = aggregate(Flow_XTS,list(Index = cut(index(Flow_XTS), breaks="day")),mean, na.rm = TRUE)
  n = 5
  fiveday = aggregate(daily,list(rep(1:(nrow(daily)%/%n),each=n,len=nrow(daily))),min, na.rm=T)
  f1=as.numeric(fiveday)
  f2=0.9*f1
  f3=NULL
  i=NULL
  n1=length(f1)
  for(i in seq(2,n1-1,1)){
    f3[1]=f1[1]
    f3[n1]=f1[n1]
    if(f2[i]<f1[i-1] & f2[i]<f1[i+1]){
      f3[i]=f1[i]
    }else{
      f3[i]=NA
    }
  }

  f3=na.approx(f3, na.rm=FALSE)

  c1=as.data.frame(daily);c2=as.data.frame(fiveday)
  c3=as.data.frame(ifelse(c1[,1] %in% c2[,1],c1[,1],NA))
  c3=as.data.frame(cbind(c1,c3)); n=nrow(c3)
  c3[1,2]=c3[1,1];c3[n,2]=c3[n,1];c3[,2]=FillNaValues(c3[,2], maxgap = 10)
  c3[,3]=ifelse(c3[,1] %in% f3,c3[,1],NA)
  c3[1,3]=c3[1,1];c3[n,3]=c3[n,1];c3[,3]=FillNaValues(c3[,3], maxgap = 100)
  colnames(c3)=c("daily","fivedayminima","baseflow")
  c3[,3]=ifelse(c3[,3] > c3[,2],c3[,2],c3[,3]); c3[,3]=FillNaValues(c3[,3], maxgap = 100)

  c4=sum(c3[,3]) ## area under baseflow curve

  c5=sum(c3[,1]) ## area under daily mean curve

  BFI=c4/c5

  result=list(BFI,c3)
  names(result)=c("BFI","baseflow")
  return(result)
}
